# Default values for java-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: venkatalolla/maven-tekton-app
  tag: 052fb83a81d12f62b78c79893eb083b0c0f1ae63

deployment:
  containerPort: 8080

service:
  name: https
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: hello.levvel-labs.io
  routePath: /java-app
#   annotations: {}
#   path: /
#   hosts:
#     - chart-example.local
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local