apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "java-app.fullname" . }}
  labels: 
{{ include "java-app.labels" . | indent 4 }}
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  port:
    targetPort: {{ .Values.service.portName }}
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: {{ template "java-app.fullname" . }}
    weight: 100
  wildcardPolicy: None