apiVersion: v1
kind: Service
metadata:
  name: {{ template "java-app.fullname" . }}
  labels: 
{{ include "java-app.labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: {{ .Values.service.portName }}
    targetPort: {{ .Values.deployment.containerPort }}
  selector:
{{ include "java-app.labels" . | indent 6 }}
  type: {{ .Values.service.type }}