apiVersion: v1
kind: Service
metadata:
  name: sample-java-service
spec:
  ports:
  - port: {{ .Values.servcie.port }}
    name: webui
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.servcie.port }}