apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
{{ include "java-app.labels" . | indent 4 }}
  name: {{ template "java-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "java-app.labels" . | indent 6 }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "java-app.labels" . | indent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Release.Name }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.deployment.containerPort }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}